In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
preprocessing.LabelEncoder()
import random
import warnings
warnings .filterwarnings("ignore")

In [2]:
df = pd.read_csv(r"/content/diabetic_data.csv", header=[0])

In [3]:
df

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101761,443847548,100162476,AfricanAmerican,Male,[70-80),?,1,3,7,3,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101762,443847782,74694222,AfricanAmerican,Female,[80-90),?,1,4,5,5,...,No,Steady,No,No,No,No,No,No,Yes,NO
101763,443854148,41088789,Caucasian,Male,[70-80),?,1,1,7,1,...,No,Down,No,No,No,No,No,Ch,Yes,NO
101764,443857166,31693671,Caucasian,Female,[80-90),?,2,3,7,10,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101765,443867222,175429310,Caucasian,Male,[70-80),?,1,1,7,6,...,No,No,No,No,No,No,No,No,No,NO

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   weight                    101766 non-null  object
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  object
 11  medical_specialty         101766 non-null  object
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  object
 19  diag_2                    101766 non-null  object
 20  diag_3                    101766 non-null  object
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    object
 23  A1Cresult                 17018 non-null   object
 24  metformin                 101766 non-null  object
 25  repaglinide               101766 non-null  object
 26  nateglinide               101766 non-null  object
 27  chlorpropamide            101766 non-null  object
 28  glimepiride               101766 non-null  object
 29  acetohexamide             101766 non-null  object
 30  glipizide                 101766 non-null  object
 31  glyburide                 101766 non-null  object
 32  tolbutamide               101766 non-null  object
 33  pioglitazone              101766 non-null  object
 34  rosiglitazone             101766 non-null  object
 35  acarbose                  101766 non-null  object
 36  miglitol                  101766 non-null  object
 37  troglitazone              101766 non-null  object
 38  tolazamide                101766 non-null  object
 39  examide                   101766 non-null  object
 40  citoglipton               101766 non-null  object
 41  insulin                   101766 non-null  object
 42  glyburide-metformin       101766 non-null  object
 43  glipizide-metformin       101766 non-null  object
 44  glimepiride-pioglitazone  101766 non-null  object
 45  metformin-rosiglitazone   101766 non-null  object
 46  metformin-pioglitazone    101766 non-null  object
 47  change                    101766 non-null  object
 48  diabetesMed               101766 non-null  object
 49  readmitted                101766 non-null  object
dtypes: int64(13), object(37)
memory usage: 38.8+ MB

In [5]:
df.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          0
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [6]:
# df['max_glu_serum']
df['A1Cresult']

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
101761     >8
101762    NaN
101763    NaN
101764    NaN
101765    NaN
Name: A1Cresult, Length: 101766, dtype: object

In [ ]:
# for i in range (50):
#     m=df.iloc[:, i].value_counts()
#     print(m)

In [7]:
# Replace the values of 'None' to real value
df['max_glu_serum'].fillna(0,inplace=True)
df['max_glu_serum']=df['max_glu_serum'].replace({'None':'0','Norm':'1','>200':'2','>300':'3'})
# df['max_glu_serum']

In [8]:
# Replace the values of 'None' to real value
df['A1Cresult'].fillna(0,inplace=True)
df['A1Cresult']=df['A1Cresult'].replace({'None':'0','Norm':'1','>200':'2','>300':'3','>8':'4','>7':'5'})
# df['A1Cresult']

In [9]:
# Treatement The Missing Value
df['race']=df['race'].replace({'?':'Caucasian'})
df['weight']=df['weight'].replace({'?':'[75-100)'})
df['payer_code']=df['payer_code'].replace({'?':'Not Known'})
df['medical_specialty']=df['medical_specialty'].replace({'?':'Not Known'})
df['diag_1']=df['diag_1'].replace({'?':'428','V57':'0','V58':'1','V55':'2','V54':'3','V53':'4','V56':'5','V71':'6','V63':'7','V45':'8','V66':'9','V26':'10','V67':'11','V60':'12','V43':'13','V25':'14','V70':'15','E909':'16','V07':'17','V51':'18'})
df['diag_2']=df['diag_2'].replace({'?':'276','V42': '0', 'V85': '1', 'V15': '2', 'E878': '3', 'E885': '4', 'E888': '5', 'V10': '6','V12': '7', 'V62': '8', 'E849': '9', 'V49': '10', 'E932': '11', 'E942': '12', 'V64': '13','E935': '14', 'V65': '15', 'E947': '16', 'E884': '17', 'E879': '18', 'E880': '19', 'E928': '20','E939': '21', 'V72': '22', 'V46': '23', 'E944': '24', 'V44': '25', 'E934': '26', 'E950': '27','V09': '28', 'V17': '29', 'E930': '30', 'V18': '31', 'E812': '32', 'V08': '33', 'E936': '34','E927': '35', 'E917': '36', 'E937': '37', 'E933': '38', 'E858': '39', 'E881': '40', 'V02': '41','E870': '42', 'E887': '43', 'E924': '44', 'E931': '45', 'E906': '46', 'E905': '47', 'E816': '48','V14': '49', 'V23': '50', 'E916': '51', 'V16': '52', 'E853': '53', 'V61': '54', 'E814': '55','V11': '56', 'E941': '57', 'E821': '58', 'V86': '59', 'E819': '60', 'E968': '61', 'V03': '62','E882': '63', 'V50': '64', 'E980': '65', 'E818': '66', 'E938': '67', 'V69': '68', 'E945': '69','E900': '70', 'E826': '71', 'E919': '72', 'E829': '73', 'E850': '74', 'V13': '75', 'E918': '76','E854': '77', 'E868': '78', 'E813': '79', 'E965': '80', 'E929': '81', 'E817': '82', 'E890': '83','E915': '84', 'E883': '85' ,'V45':'86',
'V58':'87',
'V43' :'88',
'V54':'89',
'V63':'90',
'V57':'91',
'V70':'92',
'V66':'93',
'V53':'94',
'V55':'95',
'V25':'96',
'V60':'97'})


df['diag_3']=df['diag_3'].replace({'?':'250','V15': '0', 'V42': '1', 'V10': '2', 'E849': '3', 'V12': '4', 'E878': '5', 'E888': '6', 'E885': '7', 'V85': '8', 'V09': '9', 'E932': '10', 'V46': '11', 'E879': '12', 'V49': '13', 'E942': '14', 'V64': '15', 'E947': '16', 'V27': '17', 'E935': '18', 'V62': '19', 'V44': '20', 'E880': '21', 'V65': '22', 'E884': '23', 'V17': '24', 'E934': '25', 'E812': '26', 'E944': '27', 'E939': '28', 'V08': '29', 'E950': '30', 'E933': '31', 'V18': '32', 'E930': '33', 'V14': '34', 'E931': '35', 'E928': '36', 'E881': '37', 'E816': '38', 'E819': '39', 'V72': '40', 'V16': '41', 'E870': '42', 'E936': '43', 'E929': '44', 'E927': '45', 'E887': '46', 'E937': '47', 'E938': '48', 'E941': '49', 'V03': '50', 'E850': '51', 'E906': '52', 'V61': '53', 'V13': '54', 'E858': '55', 'V23': '56', 'V02': '57', 'E818': '58', 'E917': '59', 'E916': '60', 'V86': '61', 'E905': '62', 'E920': '63', 'E980': '64', 'E956': '65', 'E943': '66', 'V11': '67', 'E852': '68', 'E813': '69', 'E901': '70', 'E919': '71', 'E817': '72', 'E855': '73', 'V06': '74', 'E924': '75', 'E946': '76', 'E955': '77', 'E912': '78', 'E865': '79', 'E987': '80', 'E886': '81', 'E892': '82', 'E864': '83', 'E825': '84', 'E922': '85', 'E966': '86', 'E900': '87', 'E949': '88', 'E876': '89', 'E828': '90', 'E853': '91', 'V01': '92', 'E915': '93', 'E894': '94', 'E826': '95', 'E945': '96', 'E822': '97', 'E882': '98', 'E904': '99', 'E815': '100', 'E965': '101', 'E861': '102', 'E883': '103', 'V22': '104', 'E854': '105' , 'V45':'106',
'V58':'107',
'V43':'108',
'V54':'109',
'V66':'110',
'V63':'111',
'V55':'112',
'V57':'113',
'V53':'114',
'V60':'115',
'V70':'116',
'V25':'117',
'V07':'118',})

In [ ]:
# M=df[1].value_counts()
# print(M)
for i in range (50):
    m=df.iloc[:, i].value_counts()
    print(m)

encounter_id
2278392      1
190792044    1
190790070    1
190789722    1
190786806    1
            ..
106665324    1
106657776    1
106644876    1
106644474    1
443867222    1
Name: count, Length: 101766, dtype: int64
patient_nbr
88785891     40
43140906     28
1660293      23
88227540     23
23199021     23
             ..
11005362      1
98252496      1
1019673       1
13396320      1
175429310     1
Name: count, Length: 71518, dtype: int64
race
Caucasian          78372
AfricanAmerican    19210
Hispanic            2037
Other               1506
Asian                641
Name: count, dtype: int64
gender
Female             54708
Male               47055
Unknown/Invalid        3
Name: count, dtype: int64
age
[70-80)     26068
[60-70)     22483
[50-60)     17256
[80-90)     17197
[40-50)      9685
[30-40)      3775
[90-100)     2793
[20-30)      1657
[10-20)       691
[0-10)        161
Name: count, dtype: int64
weight
[75-100)     99905
[50-75)        897
[100-125)      625
[125-150)      145
[25-50)         97
[0-25)          48
[150-175)       35
[175-200)       11
>200             3
Name: count, dtype: int64
admission_type_id
1    53990
3    18869
2    18480
6     5291
5     4785
8      320
7       21
4       10
Name: count, dtype: int64
discharge_disposition_id
1     60234
3     13954
6     12902
18     3691
2      2128
22     1993
11     1642
5      1184
25      989
4       815
7       623
23      412
13      399
14      372
28      139
8       108
15       63
24       48
9        21
17       14
16       11
19        8
10        6
27        5
12        3
20        2
Name: count, dtype: int64
admission_source_id
7     57494
1     29565
17     6781
4      3187
6      2264
2      1104
5       855
3       187
20      161
9       125
8        16
22       12
10        8
14        2
11        2
25        2
13        1
Name: count, dtype: int64
time_in_hospital
3     17756
2     17224
1     14208
4     13924
5      9966
6      7539
7      5859
8      4391
9      3002
10     2342
11     1855
12     1448
13     1210
14     1042
Name: count, dtype: int64
payer_code
Not Known    40256
MC           32439
HM            6274
SP            5007
BC            4655
MD            3532
CP            2533
UN            2448
CM            1937
OG            1033
PO             592
DM             549
CH             146
WC             135
OT              95
MP              79
SI              55
FR               1
Name: count, dtype: int64
medical_specialty
Not Known                        49949
InternalMedicine                 14635
Emergency/Trauma                  7565
Family/GeneralPractice            7440
Cardiology                        5352
                                 ...
SportsMedicine                       1
Speech                               1
Perinatology                         1
Neurophysiology                      1
Pediatrics-InfectiousDiseases        1
Name: count, Length: 73, dtype: int64
num_lab_procedures
1      3208
43     2804
44     2496
45     2376
38     2213
       ...
120       1
132       1
121       1
126       1
118       1
Name: count, Length: 118, dtype: int64
num_procedures
0    46652
1    20742
2    12717
3     9443
6     4954
4     4180
5     3078
Name: count, dtype: int64
num_medications
13    6086
12    6004
11    5795
15    5792
14    5707
      ...
70       2
75       2
81       1
79       1
74       1
Name: count, Length: 75, dtype: int64
number_outpatient
0     85027
1      8547
2      3594
3      2042
4      1099
5       533
6       303
7       155
8        98
9        83
10       57
11       42
13       31
12       30
14       28
15       20
16       15
17        8
21        7
20        7
18        5
22        5
19        3
27        3
24        3
26        2
23        2
25        2
33        2
35        2
36        2
29        2
34        1
39        1
42        1
28        1
37        1
38        1
40        1
Name: count, dtype: int64
number_emergency
0     90383
1      7677
2      2042
3       725
4       374
5       192
6        94
7        73
8        50
10       34
9        33
11       23
13       12
12       10
22        6
16        5
18        5
19        4
20        4
15        3
14        3
25        2
21        2
28        1
42        1
46        1
76        1
37        1
64        1
63        1
54        1
24        1
29        1
Name: count, dtype: int64
number_inpatient
0     67630
1     19521
2      7566
3      3411
4      1622
5       812
6       480
7       268
8       151
9       111
10       61
11       49
12       34
13       20
14       10
15        9
16        6
19        2
17        1
21        1
18        1
Name: count, dtype: int64
diag_1
428    6883
414    6581
786    4016
410    3614
486    3508
       ...
885       1
57        1
314       1
684       1
18        1
Name: count, Length: 709, dtype: int64
diag_2
276    7110
428    6662
250    6071
427    5036
401    3736
       ...
130       1
734       1
968       1
754       1
927       1
Name: count, Length: 723, dtype: int64
diag_3
250    12978
401     8289
276     5175
428     4577
427     3955
       ...
100        1
884        1
195        1
872        1
971        1
Name: count, Length: 758, dtype: int64
number_diagnoses
9     49474
5     11393
8     10616
7     10393
6     10161
4      5537
3      2835
2      1023
1       219
16       45
10       17
13       16
11       11
15       10
12        9
14        7
Name: count, dtype: int64
max_glu_serum
0    96420
1     2597
2     1485
3     1264
Name: count, dtype: int64
A1Cresult
0    84748
4     8216
1     4990
5     3812
Name: count, dtype: int64
metformin
No        81778
Steady    18346
Up         1067
Down        575
Name: count, dtype: int64
repaglinide
No        100227
Steady      1384
Up           110
Down          45
Name: count, dtype: int64
nateglinide
No        101063
Steady       668
Up            24
Down          11
Name: count, dtype: int64
chlorpropamide
No        101680
Steady        79
Up             6
Down           1
Name: count, dtype: int64
glimepiride
No        96575
Steady     4670
Up          327
Down        194
Name: count, dtype: int64
acetohexamide
No        101765
Steady         1
Name: count, dtype: int64
glipizide
No        89080
Steady    11356
Up          770
Down        560
Name: count, dtype: int64
glyburide
No        91116
Steady     9274
Up          812
Down        564
Name: count, dtype: int64
tolbutamide
No        101743
Steady        23
Name: count, dtype: int64
pioglitazone
No        94438
Steady     6976
Up          234
Down        118
Name: count, dtype: int64
rosiglitazone
No        95401
Steady     6100
Up          178
Down         87
Name: count, dtype: int64
acarbose
No        101458
Steady       295
Up            10
Down           3
Name: count, dtype: int64
miglitol
No        101728
Steady        31
Down           5
Up             2
Name: count, dtype: int64
troglitazone
No        101763
Steady         3
Name: count, dtype: int64
tolazamide
No        101727
Steady        38
Up             1
Name: count, dtype: int64
examide
No    101766
Name: count, dtype: int64
citoglipton
No    101766
Name: count, dtype: int64
insulin
No        47383
Steady    30849
Down      12218
Up        11316
Name: count, dtype: int64
glyburide-metformin
No        101060
Steady       692
Up             8
Down           6
Name: count, dtype: int64
glipizide-metformin
No        101753
Steady        13
Name: count, dtype: int64
glimepiride-pioglitazone
No        101765
Steady         1
Name: count, dtype: int64
metformin-rosiglitazone
No        101764
Steady         2
Name: count, dtype: int64
metformin-pioglitazone
No        101765
Steady         1
Name: count, dtype: int64
change
No    54755
Ch    47011
Name: count, dtype: int64
diabetesMed
Yes    78363
No     23403
Name: count, dtype: int64
readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

In [10]:
df['race']=df['race'].replace({'Caucasian':'0','AfricanAmerican':'1','Hispanic':'2','Other':'3','Asian':'4'})
df['metformin']=df['metformin'].replace({'No':'0','Steady':'1','Up':'2','Down':'3'})
df['repaglinide']=df['repaglinide'].replace({'No':'0','Steady':'1','Up':'2','Down':'3'})
df['nateglinide']=df['nateglinide'].replace({'No':'0','Steady':'1','Up':'2','Down':'3'})
df['chlorpropamide']=df['chlorpropamide'].replace({'No':'0','Steady':'1','Up':'2','Down':'3'})
df['glimepiride']=df['glimepiride'].replace({'No':'0','Steady':'1','Up':'2','Down':'3'})
df['acetohexamide']=df['acetohexamide'].replace({'No':'0','Steady':'1'})
df['glipizide']=df['glipizide'].replace({'No':'0','Steady':'1','Up':'2','Down':'3'})
df['glyburide']=df['glyburide'].replace({'No':'0','Steady':'1','Up':'2','Down':'3'})
df['tolbutamide']=df['tolbutamide'].replace({'No':'0','Steady':'1'})
df['pioglitazone']=df['pioglitazone'].replace({'No':'0','Steady':'1','Up':'2','Down':'3'})
df['rosiglitazone']=df['rosiglitazone'].replace({'No':'0','Steady':'1','Up':'2','Down':'3'})
df['acarbose']=df['acarbose'].replace({'No':'0','Steady':'1','Up':'2','Down':'3'})
df['miglitol']=df['miglitol'].replace({'No':'0','Steady':'1','Up':'2','Down':'3'})
df['troglitazone']=df['troglitazone'].replace({'No':'0','Steady':'1'})
df['tolazamide']=df['tolazamide'].replace({'No':'0','Steady':'1','Up':'2'})
df['examide']=df['examide'].replace({'No':'0'})
df['citoglipton']=df['citoglipton'].replace({'No':'0'})
df['insulin']=df['insulin'].replace({'No':'0','Steady':'1','Up':'2','Down':'3'})
df['glyburide-metformin']=df['glyburide-metformin'].replace({'No':'0','Steady':'1','Up':'2','Down':'3'})
df['glipizide-metformin']=df['glipizide-metformin'].replace({'No':'0','Steady':'1'})
df['glimepiride-pioglitazone']=df['glimepiride-pioglitazone'].replace({'No':'0','Steady':'1'})
df['metformin-rosiglitazone']=df['metformin-rosiglitazone'].replace({'No':'0','Steady':'1'})
df['metformin-pioglitazone']=df['metformin-pioglitazone'].replace({'No':'0','Steady':'1'})
df['change']=df['change'].replace({'No':'0','Ch':'1'})
df['diabetesMed']=df['diabetesMed'].replace({'No':'0','Yes':'1'})
df['readmitted']=df['readmitted'].replace({'NO':'0','>30':'1','<30':'2'})
df['gender']=df['gender'].replace({'Female':'0','Male':'1','Unknown/Invalid':'2'})
df['age']=df['age'].replace({'[0-10)':'0','[10-20)':'1','[20-30)':'2','[30-40)':'3','[40-50)':'4','[50-60)':'5','[60-70)':'6','[70-80)':'7','[80-90)':'8','[90-100)':'9'})
df['weight']=df['weight'].replace({'[0-25)':'0','[25-50)':'1','[50-75)':'2','[75-100)':'3','[100-125)':'4','[125-150)':'5','[150-175)':'6','[175-200)':'7','>200':'8'})

In [ ]:
df

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,0,0,0,3,6,25,1,1,...,0,0,0,0,0,0,0,0,0,0
1,149190,55629189,0,0,1,3,1,1,7,3,...,0,2,0,0,0,0,0,1,1,1
2,64410,86047875,1,0,2,3,1,1,7,2,...,0,0,0,0,0,0,0,0,1,0
3,500364,82442376,0,1,3,3,1,1,7,2,...,0,2,0,0,0,0,0,1,1,0
4,16680,42519267,0,1,4,3,1,1,7,1,...,0,1,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101761,443847548,100162476,1,1,7,3,1,3,7,3,...,0,3,0,0,0,0,0,1,1,1
101762,443847782,74694222,1,0,8,3,1,4,5,5,...,0,1,0,0,0,0,0,0,1,0
101763,443854148,41088789,0,1,7,3,1,1,7,1,...,0,3,0,0,0,0,0,1,1,0
101764,443857166,31693671,0,0,8,3,2,3,7,10,...,0,2,0,0,0,0,0,1,1,0
101765,443867222,175429310,0,1,7,3,1,1,7,6,...,0,0,0,0,0,0,0,0,0,0

In [11]:
y= df['readmitted']
y=y.astype(float)

In [ ]:
df.isnull().sum()

encounter_id                0
patient_nbr                 0
race                        0
gender                      0
age                         0
weight                      0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
payer_code                  0
medical_specialty           0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
max_glu_serum               0
A1Cresult                   0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazone                0
rosiglitazone               0
acarbose                    0
miglitol                    0
troglitazone                0
tolazamide                  0
examide                     0
citoglipton                 0
insulin                     0
glyburide-metformin         0
glipizide-metformin         0
glimepiride-pioglitazone    0
metformin-rosiglitazone     0
metformin-pioglitazone      0
change                      0
diabetesMed                 0
readmitted                  0
dtype: int64

In [ ]:
def calaculate_accuracy(x):
    X=df[x]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.30)
    lgt_R = LogisticRegression(solver='lbfgs')
    lgt_R.fit(X_train, y_train)
    accuracy=lgt_R.score(X_test,y_test)
    print('Accuracy:',accuracy)
    return accuracy

In [12]:
columnsName=df.drop(labels= {'readmitted','payer_code','medical_specialty'}, axis= 1).columns.values.tolist()

In [ ]:
print(columnsName)

['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight', 'admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton', 'insulin', 'glyburide-metformin', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed']

In [ ]:
columnsName1=[0,1]
chromosomes=[]
for i in range(10):
    chro1=[]
    for i in range(47):
        item = random.choice(tuple(columnsName1))
        chro1.append(item)
    chromosomes.append(chro1)

In [ ]:
def data(chromosomes1):
    chromosomes2=[]
    for i in range(len(chromosomes1)):
        if chromosomes1[i]==1:
                chromosomes2.append(columnsName[i])
    return chromosomes2

In [13]:
nonintcolumns = df.columns[24:]
df[nonintcolumns]=df[nonintcolumns].astype('int64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   weight                    101766 non-null  object
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  object
 11  medical_specialty         101766 non-null  object
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  object
 19  diag_2                    101766 non-null  object
 20  diag_3                    101766 non-null  object
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             101766 non-null  object
 23  A1Cresult                 101766 non-null  object
 24  metformin                 101766 non-null  int64
 25  repaglinide               101766 non-null  int64
 26  nateglinide               101766 non-null  int64
 27  chlorpropamide            101766 non-null  int64
 28  glimepiride               101766 non-null  int64
 29  acetohexamide             101766 non-null  int64
 30  glipizide                 101766 non-null  int64
 31  glyburide                 101766 non-null  int64
 32  tolbutamide               101766 non-null  int64
 33  pioglitazone              101766 non-null  int64
 34  rosiglitazone             101766 non-null  int64
 35  acarbose                  101766 non-null  int64
 36  miglitol                  101766 non-null  int64
 37  troglitazone              101766 non-null  int64
 38  tolazamide                101766 non-null  int64
 39  examide                   101766 non-null  int64
 40  citoglipton               101766 non-null  int64
 41  insulin                   101766 non-null  int64
 42  glyburide-metformin       101766 non-null  int64
 43  glipizide-metformin       101766 non-null  int64
 44  glimepiride-pioglitazone  101766 non-null  int64
 45  metformin-rosiglitazone   101766 non-null  int64
 46  metformin-pioglitazone    101766 non-null  int64
 47  change                    101766 non-null  int64
 48  diabetesMed               101766 non-null  int64
 49  readmitted                101766 non-null  int64
dtypes: int64(39), object(11)
memory usage: 38.8+ MB

In [14]:
df['gender']=df['gender'].astype('int64')
df['age']=df['age'].astype('int64')
df['weight']=df['weight'].astype('int64')
df['race']=df['race'].astype('int64')
df['max_glu_serum']=df['max_glu_serum'].astype('int64')
# df['A1Cresult']=df['A1Cresult'].astype('int64')
df['diag_1']=df['diag_1'].astype(float)
df['diag_2']=df['diag_2'].astype(float)
df['diag_3']=df['diag_3'].astype(float)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  int64
 3   gender                    101766 non-null  int64
 4   age                       101766 non-null  int64
 5   weight                    101766 non-null  int64
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  object
 11  medical_specialty         101766 non-null  object
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  float64
 19  diag_2                    101766 non-null  float64
 20  diag_3                    101766 non-null  float64
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             101766 non-null  int64
 23  A1Cresult                 101766 non-null  object
 24  metformin                 101766 non-null  int64
 25  repaglinide               101766 non-null  int64
 26  nateglinide               101766 non-null  int64
 27  chlorpropamide            101766 non-null  int64
 28  glimepiride               101766 non-null  int64
 29  acetohexamide             101766 non-null  int64
 30  glipizide                 101766 non-null  int64
 31  glyburide                 101766 non-null  int64
 32  tolbutamide               101766 non-null  int64
 33  pioglitazone              101766 non-null  int64
 34  rosiglitazone             101766 non-null  int64
 35  acarbose                  101766 non-null  int64
 36  miglitol                  101766 non-null  int64
 37  troglitazone              101766 non-null  int64
 38  tolazamide                101766 non-null  int64
 39  examide                   101766 non-null  int64
 40  citoglipton               101766 non-null  int64
 41  insulin                   101766 non-null  int64
 42  glyburide-metformin       101766 non-null  int64
 43  glipizide-metformin       101766 non-null  int64
 44  glimepiride-pioglitazone  101766 non-null  int64
 45  metformin-rosiglitazone   101766 non-null  int64
 46  metformin-pioglitazone    101766 non-null  int64
 47  change                    101766 non-null  int64
 48  diabetesMed               101766 non-null  int64
 49  readmitted                101766 non-null  int64
dtypes: float64(3), int64(44), object(3)
memory usage: 38.8+ MB

In [ ]:
pb=[]
def checkpersonalnest():
    for i in range(len(chromosomes)):
         pb.append(calaculate_accuracy(data(chromosomes[i])))
checkpersonalnest()

Accuracy: 0.5395348837209303
Accuracy: 0.5693088765149034
Accuracy: 0.5685555191614805
Accuracy: 0.5415984277759581
Accuracy: 0.5412053717654766
Accuracy: 0.5360628889616771
Accuracy: 0.5389780543727481
Accuracy: 0.547101211922699
Accuracy: 0.5414018997707173
Accuracy: 0.5635440550278414

In [ ]:
df.iloc[:, 18].value_counts()

diag_1
428.0    6883
414.0    6581
786.0    4016
410.0    3614
486.0    3508
         ...
885.0       1
57.0        1
314.0       1
684.0       1
18.0        1
Name: count, Length: 709, dtype: int64

In [ ]:
import re

# Assuming df is your DataFrame and 'column_name' is the column you want to count
# Convert the column to string type if it's not already
df['diag_3'] = df['diag_3'].astype(str)

# Define a regular expression pattern to match numeric values
numeric_pattern = r'^-?\d*\.?\d+$'

# Use the regular expression to filter out numeric values
non_numeric_values = df[~df['diag_3'].str.match(numeric_pattern)]

# Tokenize the non-numeric values into words
words = non_numeric_values['diag_3'].str.split()

# Count the number of non-numeric words
word_count = sum(len(word) for word in words)

print("Number of non-numeric words:", word_count)


# for word in words:
#     print(word)
pd.set_option('display.max_rows',None)
print(words.value_counts())

Number of non-numeric words: 0
Series([], Name: count, dtype: int64)

In [ ]:
def checkvelocity(globalbest):
    velocity=[]
    for j in range(len(chromosomes)):
        velocity.append(list(0+1*(np.random.random(1)[0])*(np.array(chromosomes[j])-np.array(chromosomes[j]))+1*(np.random.random(1)[0])*(np.array(globalbest)-np.array(chromosomes[j]))))
    #print(velocity)
    return velocity

In [ ]:
def addingchromosomes(velocity):
    chromosomes2=[]
    for i in range(len(velocity)):
        nextchromo=[]
        for j in range(len(velocity[i])):
            nextchromo.append(chromosomes[i][j]+velocity[i][j])
        chromosomes2.append(nextchromo)
    return chromosomes2

In [ ]:
def normalize(chromosomes2):
    for l in range(len(chromosomes2)):
        for m in range(len(chromosomes2[l])):
            if chromosomes2[l][m]>0.5:
                chromosomes2[l][m]=1
            else:
                chromosomes2[l][m]=0
    return chromosomes2

In [ ]:
def checkpd(chromosomes2):
    personal=[]
    for i in range(len(chromosomes2)):
        personal.append(calaculate_accuracy(data(chromosomes2[i])))
    for j in range(len(personal)):
        if(personal[j]>pb[j]):
            chromosomes[j]=chromosomes2[j]
            pb[j]=personal[j]
    return personal

In [ ]:
max(pb)
ind = pb.index(max(pb))
globalbest=chromosomes[ind]
for i in range(20):
    chromosomes2=[]
    personal=[]
    velocity=checkvelocity(globalbest)
    chromosomes2=addingchromosomes(velocity)
    chromosomes2=normalize(chromosomes2)
    personal=checkpd(chromosomes2)
    globalbest=[]
    max(pb)
    ind = pb.index(max(pb))
    globalbest=chromosomes[ind]

Accuracy: 0.5645594497215853
Accuracy: 0.5653783164100884
Accuracy: 0.5650835244022273
Accuracy: 0.5417294464461185
Accuracy: 0.5698329511955453
Accuracy: 0.5395021290533901
Accuracy: 0.5420569931215198
Accuracy: 0.5634457910252211
Accuracy: 0.5592859482476253
Accuracy: 0.5637078283655421
Accuracy: 0.5645922043891255
Accuracy: 0.5643301670488045
Accuracy: 0.5625614150016377
Accuracy: 0.5617425483131346
Accuracy: 0.565280052407468
Accuracy: 0.5659351457582705
Accuracy: 0.5365869636423191
Accuracy: 0.56580412708811
Accuracy: 0.5673435964624959
Accuracy: 0.5691451031772028
Accuracy: 0.5680969538159187
Accuracy: 0.565280052407468
Accuracy: 0.5675728791352768
Accuracy: 0.5666885031116934
Accuracy: 0.5686210284965607
Accuracy: 0.565247297739928
Accuracy: 0.5658368817556502
Accuracy: 0.5582705535538814
Accuracy: 0.5624959056665575
Accuracy: 0.5626596790042581
Accuracy: 0.5659023910907305
Accuracy: 0.5662626924336718
Accuracy: 0.5700949885358664
Accuracy: 0.5655093350802489
Accuracy: 0.5600393056010482
Accuracy: 0.565247297739928
Accuracy: 0.5668850311169341
Accuracy: 0.565247297739928
Accuracy: 0.5681297084834589
Accuracy: 0.5643629217163446
Accuracy: 0.5652145430723878
Accuracy: 0.5705863085489682
Accuracy: 0.5612839829675729
Accuracy: 0.5680641991483787
Accuracy: 0.5617753029806748
Accuracy: 0.5659023910907305
Accuracy: 0.5645266950540452
Accuracy: 0.5662299377661316
Accuracy: 0.5707500818866689
Accuracy: 0.5661316737635113
Accuracy: 0.5648542417294464
Accuracy: 0.5662299377661316
Accuracy: 0.5669177857844743
Accuracy: 0.5641663937111039
Accuracy: 0.5669177857844743
Accuracy: 0.5650180150671471
Accuracy: 0.5667540124467737
Accuracy: 0.5659679004258107
Accuracy: 0.5679331804782182
Accuracy: 0.5676056338028169
Accuracy: 0.5640681297084834
Accuracy: 0.5674746151326564
Accuracy: 0.569734687192925
Accuracy: 0.5674418604651162
Accuracy: 0.5678021618080576
Accuracy: 0.5660334097608909
Accuracy: 0.5680314444808385
Accuracy: 0.5672125777923354
Accuracy: 0.563937111038323
Accuracy: 0.5668195217818539
Accuracy: 0.5649525057320668
Accuracy: 0.5649197510645267
Accuracy: 0.5690795938421225
Accuracy: 0.5678349164755978
Accuracy: 0.5629544710121193
Accuracy: 0.5716999672453325
Accuracy: 0.5679659351457582
Accuracy: 0.5647559777268261
Accuracy: 0.5659351457582705
Accuracy: 0.5667867671143137
Accuracy: 0.5665247297739928
Accuracy: 0.5658368817556502
Accuracy: 0.5705863085489682
Accuracy: 0.5669832951195546
Accuracy: 0.5656075990828693
Accuracy: 0.5655420897477891
Accuracy: 0.5672453324598755
Accuracy: 0.5659679004258107
Accuracy: 0.5700294792007861
Accuracy: 0.5686537831641009
Accuracy: 0.5666557484441533
Accuracy: 0.5643301670488045
Accuracy: 0.5685555191614805
Accuracy: 0.5661316737635113
Accuracy: 0.5638060923681625
Accuracy: 0.5627906976744186
Accuracy: 0.5641008843760236
Accuracy: 0.5693088765149034
Accuracy: 0.5633802816901409
Accuracy: 0.565280052407468
Accuracy: 0.563969865705863
Accuracy: 0.5655093350802489
Accuracy: 0.5654110710776286
Accuracy: 0.568162463150999
Accuracy: 0.5672453324598755
Accuracy: 0.5625941696691779
Accuracy: 0.5625614150016377
Accuracy: 0.5671470684572552
Accuracy: 0.5643629217163446
Accuracy: 0.568948575171962
Accuracy: 0.5623321323288568
Accuracy: 0.5682607271536194
Accuracy: 0.5695381591876842
Accuracy: 0.5651817884048477
Accuracy: 0.5662954471012119
Accuracy: 0.5683262364886996
Accuracy: 0.5704552898788078
Accuracy: 0.564985260399607
Accuracy: 0.5640353750409434
Accuracy: 0.5708811005568294
Accuracy: 0.5667540124467737
Accuracy: 0.5660006550933508
Accuracy: 0.564493940386505
Accuracy: 0.5675073698001966
Accuracy: 0.5677038978054373
Accuracy: 0.5650835244022273
Accuracy: 0.5646577137242057
Accuracy: 0.5628234523419587
Accuracy: 0.5644284310514248
Accuracy: 0.5644284310514248
Accuracy: 0.5674746151326564
Accuracy: 0.563675073698002
Accuracy: 0.5701604978709466
Accuracy: 0.5663937111038323
Accuracy: 0.568948575171962
Accuracy: 0.5641336390435637
Accuracy: 0.5647559777268261
Accuracy: 0.5674091057975762
Accuracy: 0.5662954471012119
Accuracy: 0.5651490337373075
Accuracy: 0.5659023910907305
Accuracy: 0.5638388470357026
Accuracy: 0.5696691778578448
Accuracy: 0.5669832951195546
Accuracy: 0.5660989190959712
Accuracy: 0.5688830658368818
Accuracy: 0.5651817884048477
Accuracy: 0.5648542417294464
Accuracy: 0.5678349164755978
Accuracy: 0.567081559122175
Accuracy: 0.5656403537504094
Accuracy: 0.5636095643629218
Accuracy: 0.5599082869308877
Accuracy: 0.5702915165411071
Accuracy: 0.5629217163445791
Accuracy: 0.5679331804782182
Accuracy: 0.5634457910252211
Accuracy: 0.567900425810678
Accuracy: 0.5677366524729774
Accuracy: 0.5625286603340977
Accuracy: 0.5661316737635113
Accuracy: 0.5659023910907305
Accuracy: 0.564985260399607
Accuracy: 0.5632492630199804
Accuracy: 0.5637078283655421
Accuracy: 0.5637405830330822
Accuracy: 0.5677038978054373
Accuracy: 0.5638060923681625
Accuracy: 0.5688175565018015
Accuracy: 0.5669177857844743
Accuracy: 0.5692433671798232
Accuracy: 0.563675073698002
Accuracy: 0.5653128070750082
Accuracy: 0.5649525057320668
Accuracy: 0.5638716017032427
Accuracy: 0.5663282017687521
Accuracy: 0.5666557484441533
Accuracy: 0.5660334097608909
Accuracy: 0.5634785456927612
Accuracy: 0.5677694071405175
Accuracy: 0.5662954471012119
Accuracy: 0.5627579430068784
Accuracy: 0.5693088765149034
Accuracy: 0.5642974123812643
Accuracy: 0.5676056338028169
Accuracy: 0.5641336390435637
Accuracy: 0.5635440550278414
Accuracy: 0.5711103832296103
Accuracy: 0.5673435964624959
Accuracy: 0.5638716017032427
Accuracy: 0.567081559122175
Accuracy: 0.5647559777268261
Accuracy: 0.5615132656403538
Accuracy: 0.5698001965280053
Accuracy: 0.5647887323943662
Accuracy: 0.5667540124467737
Accuracy: 0.5627251883393384
Accuracy: 0.5651817884048477
Accuracy: 0.5666229937766132
Accuracy: 0.5651817884048477

In [ ]:
max(pb)

0.5716999672453325

In [ ]:
ind = pb.index(max(pb))
print(ind)
globalbest=chromosomes[ind]

5

In [ ]:
print(data(globalbest))

['race', 'weight', 'time_in_hospital', 'num_lab_procedures', 'number_outpatient', 'number_inpatient', 'diag_2', 'diag_3', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'examide', 'insulin', 'glimepiride-pioglitazone', 'metformin-pioglitazone', 'diabetesMed']

In [15]:
columns_to_keep = ['race', 'weight', 'time_in_hospital', 'num_lab_procedures', 'number_outpatient', 'number_inpatient', 'diag_2', 'diag_3', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'examide', 'insulin', 'glimepiride-pioglitazone', 'metformin-pioglitazone', 'diabetesMed']

In [22]:

# Creating a new DataFrame with only the specified columns
new_df = df[columns_to_keep].copy()

In [25]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 24 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   race                      101766 non-null  int64
 1   weight                    101766 non-null  int64
 2   time_in_hospital          101766 non-null  int64
 3   num_lab_procedures        101766 non-null  int64
 4   number_outpatient         101766 non-null  int64
 5   number_inpatient          101766 non-null  int64
 6   diag_2                    101766 non-null  float64
 7   diag_3                    101766 non-null  float64
 8   metformin                 101766 non-null  int64
 9   repaglinide               101766 non-null  int64
 10  nateglinide               101766 non-null  int64
 11  chlorpropamide            101766 non-null  int64
 12  acetohexamide             101766 non-null  int64
 13  glipizide                 101766 non-null  int64
 14  glyburide                 101766 non-null  int64
 15  tolbutamide               101766 non-null  int64
 16  pioglitazone              101766 non-null  int64
 17  rosiglitazone             101766 non-null  int64
 18  acarbose                  101766 non-null  int64
 19  examide                   101766 non-null  int64
 20  insulin                   101766 non-null  int64
 21  glimepiride-pioglitazone  101766 non-null  int64
 22  metformin-pioglitazone    101766 non-null  int64
 23  diabetesMed               101766 non-null  int64
dtypes: float64(2), int64(22)
memory usage: 18.6 MB

In [36]:
y= df['readmitted']

def calaculate_accuracy_hyperparameter(x):
    X=new_df[x]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.30)
    lgt_R = LogisticRegression(C=1.0, penalty='l2', solver='lbfgs', max_iter=100, class_weight=None, tol=0.0001, intercept_scaling=1, random_state=None)
    lgt_R.fit(X_train, y_train)
    y_pred = lgt_R.predict(X_test)

    accuracy=lgt_R.score(X_test , y_test)

    print('Accuracy:',accuracy)
    return accuracy

all_features = new_df.columns.tolist()
calaculate_accuracy_hyperparameter(all_features)

Accuracy: 0.5660334097608909

0.5660334097608909